import os
import threading
from google import genai

from app.providers.base_provider import BaseAIProvider


class GeminiProvider(BaseAIProvider):
    """
    Google Gemini implementation using google-genai SDK.
    Reuses existing GEMINI_API_KEY with timeout protection and candidate models.
    """

    MODEL = "gemini-3.1-flash-lite"

    def __init__(self, api_key=None):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.client = genai.Client(api_key=self.api_key) if self.api_key else None
        self.candidate_models = [
            "gemini-3.1-flash-lite",
            "gemini-3.6-flash",
            "gemini-flash-latest",
            "gemini-3.5-flash"
        ]

    def generate(
        self,
        system_instruction: str,
        context_facts: list,
        recent_messages: list,
        current_message: str,
        language: str = "en-IN"
    ) -> str:
        if not self.client:
            raise ValueError("GEMINI_API_KEY is not configured on the server")

        # Assemble prompt according to the specification
        facts_text = "\n".join([f"- {fact}" for fact in context_facts]) if context_facts else "No specific personal facts requested."

        history_lines = []
        for msg in recent_messages:
            role_label = "Elder" if msg.get("role") == "user" else "SmritiRoots"
            history_lines.append(f"{role_label}: {msg.get('text', '')}")
        history_text = "\n".join(history_lines) if history_lines else "No previous messages."

        lang_instruction = "Respond warmly in Hindi (Devanagari script)" if language.startswith("hi") else f"Respond warmly in {language}."

        full_prompt = f"""{system_instruction}

Language Requirement: {lang_instruction}

VERIFIED RELEVANT FACTS (Use ONLY these facts; NEVER invent family members, memories, or medical details):
{facts_text}

RECENT CONVERSATION HISTORY:
{history_text}

Elder's current message: "{current_message}"

SmritiRoots Response (concise, warm, comforting, max 2-3 short sentences for pleasant speech synthesis):"""

        def _call_models():
            last_err = None
            for model_name in self.candidate_models:
                try:
                    response = self.client.models.generate_content(
                        model=model_name,
                        contents=full_prompt
                    )
                    if response and hasattr(response, "text") and response.text:
                        return response.text.strip()
                except Exception as e:
                    last_err = e
                    print(f"[GeminiProvider] Model {model_name} attempt failed: {e}")
            if last_err:
                raise last_err
            raise RuntimeError("Empty response received from Gemini candidate models")

        # Protect against long hanging network calls with a 7-second thread timeout
        result_holder = [None]
        error_holder = [None]

        def worker():
            try:
                result_holder[0] = _call_models()
            except Exception as ex:
                error_holder[0] = ex

        thread = threading.Thread(target=worker, daemon=True)
        thread.start()
        thread.join(timeout=7.5)

        if thread.is_alive():
            raise TimeoutError("Gemini API call timed out after 7.5 seconds")

        if error_holder[0]:
            raise error_holder[0]

        if result_holder[0]:
            return result_holder[0]

        raise RuntimeError("No response generated by Gemini Provider")
